// <auto-generated />
using System;
using DaycareCenter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DaycareCenter.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200226114502_gg")]
    partial class gg
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DaycareCenter.Models.ChildProfile", b =>
                {
                    b.Property<int>("Child_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("Age")
                        .IsRequired();

                    b.Property<string>("Child_Name")
                        .IsRequired();

                    b.Property<DateTime?>("D_shiftFrom")
                        .IsRequired();

                    b.Property<DateTime?>("D_shiftTo")
                        .IsRequired();

                    b.Property<DateTime?>("End_datetime")
                        .IsRequired();

                    b.Property<string>("Gender")
                        .IsRequired();

                    b.Property<DateTime?>("M_shiftFrom")
                        .IsRequired();

                    b.Property<DateTime?>("M_shiftTo")
                        .IsRequired();

                    b.Property<string>("No_shift")
                        .IsRequired();

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.Property<string>("Religion")
                        .IsRequired();

                    b.Property<DateTime?>("Start_datetime")
                        .IsRequired();

                    b.HasKey("Child_Id");

                    b.ToTable("ChildProfile");
                });

            modelBuilder.Entity("DaycareCenter.Models.Login", b =>
                {
                    b.Property<int>("LId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Pass")
                        .IsRequired();

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LId");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("DaycareCenter.Models.NanyProfile", b =>
                {
                    b.Property<int>("Nany_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NAddress")
                        .IsRequired();

                    b.Property<string>("NAge")
                        .IsRequired();

                    b.Property<string>("NGender")
                        .IsRequired();

                    b.Property<string>("NPhone")
                        .IsRequired();

                    b.Property<string>("NReligion")
                        .IsRequired();

                    b.Property<string>("Nany_Name")
                        .IsRequired();

                    b.HasKey("Nany_Id");

                    b.ToTable("NanyProfile");
                });

            modelBuilder.Entity("DaycareCenter.Models.Payment", b =>
                {
                    b.Property<int>("Sl_No")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Hour_Rate");

                    b.Property<float>("Staying_Hour");

                    b.Property<DateTime?>("datetime")
                        .IsRequired();

                    b.Property<float>("t_Payment");

                    b.HasKey("Sl_No");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("DaycareCenter.Models.Registration", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Pass")
                        .IsRequired();

                    b.Property<string>("RePass")
                        .IsRequired();

                    b.HasKey("UserId");

                    b.ToTable("Registration");
                });
#pragma warning restore 612, 618
        }
    }
}
