// <auto-generated />
using System;
using DaycareCenter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DaycareCenter.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200404061724_dx")]
    partial class dx
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DaycareCenter.Models.ChildProfile", b =>
                {
                    b.Property<int>("Child_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("Age")
                        .IsRequired();

                    b.Property<string>("Child_Name")
                        .IsRequired();

                    b.Property<string>("Gender")
                        .IsRequired();

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.Property<string>("Religion")
                        .IsRequired();

                    b.HasKey("Child_Id");

                    b.ToTable("ChildProfile");
                });

            modelBuilder.Entity("DaycareCenter.Models.NanyProfile", b =>
                {
                    b.Property<int>("Nany_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NAddress")
                        .IsRequired();

                    b.Property<string>("NAge")
                        .IsRequired();

                    b.Property<string>("NGender")
                        .IsRequired();

                    b.Property<string>("NPhone")
                        .IsRequired();

                    b.Property<string>("NReligion")
                        .IsRequired();

                    b.Property<string>("Nany_Name")
                        .IsRequired();

                    b.HasKey("Nany_Id");

                    b.ToTable("NanyProfile");
                });

            modelBuilder.Entity("DaycareCenter.Models.NanySchedule", b =>
                {
                    b.Property<int>("Schedule_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Child_Id");

                    b.Property<int>("Nany_Id");

                    b.Property<int>("Shift_Id");

                    b.HasKey("Schedule_Id");

                    b.ToTable("NanySchedule");
                });

            modelBuilder.Entity("DaycareCenter.Models.Registration", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Pass")
                        .IsRequired();

                    b.Property<string>("RePass")
                        .IsRequired();

                    b.HasKey("UserId");

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("DaycareCenter.Models.Shift", b =>
                {
                    b.Property<int>("Shift_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("End_datetime")
                        .IsRequired();

                    b.Property<DateTime?>("Start_datetime")
                        .IsRequired();

                    b.Property<string>("shift_No")
                        .IsRequired();

                    b.Property<string>("shift_Type")
                        .IsRequired();

                    b.HasKey("Shift_Id");

                    b.ToTable("Shift");
                });
#pragma warning restore 612, 618
        }
    }
}
