// <auto-generated />
using DaycareCenter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DaycareCenter.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200225161613_dipuu")]
    partial class dipuu
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DaycareCenter.Models.Registration", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Pass")
                        .IsRequired();

                    b.Property<string>("RePass")
                        .IsRequired();

                    b.HasKey("UserId");

                    b.ToTable("Registration");
                });
#pragma warning restore 612, 618
        }
    }
}
